server:
  port: 3000

session:
  name: connect.sid
  cookie:
    path: /
    httpOnly: true
    secure: false
    maxAge: null
  secret: secret

db:
  host: 127.0.0.1
  port: 27017
  name: okusureminder
  user: okusureminder
  pass: db_pass

twitter:
  consumerKey: twitter API consumer key
  consumerSecret: twitter API consumer secret
  callbackURL: twitter API Auth Callback URL

gcm:
  api_key: google cloud messaging API key
